INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('21', 'imola', 'Autodromo Enzo e Dino Ferrari', 'Italy', '37');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('24', 'yas_marina', 'Yas Marina Circuit', 'UAE', '3');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('80', 'vegas', 'Las Vegas Strip Street Circuit', 'United States', NULL);
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('43', 'long_beach', 'Long Beach', 'USA', '12');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('38', 'brands_hatch', 'Brands Hatch', 'UK', '145');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('44', 'las_vegas', 'Las Vegas Street Circuit', 'USA', '639');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('37', 'detroit', 'Detroit Street Circuit', 'USA', '177');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('36', 'jacarepagua', 'Autodromo Internacional Nelson Piquet', 'Brazil', '1126');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('67', 'pedralbes', 'Circuit de Pedralbes', 'Spain', '85');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('59', 'boavista', 'Circuito da Boavista', 'Portugal', '28');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('30', 'kyalami', 'Kyalami', 'South Africa', '1460');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('10', 'hockenheimring', 'Hockenheimring', 'Germany', '103');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('17', 'shanghai', 'Shanghai International Circuit', 'China', '5');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('60', 'riverside', 'Riverside International Raceway', 'USA', '470');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('54', 'lemans', 'Le Mans', 'France', '67');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('53', 'essarts', 'Rouen-Les-Essarts', 'France', '81');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('4', 'catalunya', 'Circuit de Barcelona-Catalunya', 'Spain', '109');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('51', 'charade', 'Charade Circuit', 'France', '790');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('41', 'dijon', 'Dijon-Prenois', 'France', '484');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('39', 'zandvoort', 'Circuit Park Zandvoort', 'Netherlands', '6');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('71', 'sochi', 'Sochi Autodrom', 'Russia', '2');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('68', 'buddh', 'Buddh International Circuit', 'India', '194');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('79', 'miami', 'Miami International Autodrome', 'USA', NULL);
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('66', 'bremgarten', 'Circuit Bremgarten', 'Switzerland', '551');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('73', 'baku', 'Baku City Circuit', 'Azerbaijan', '-7');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('13', 'spa', 'Circuit de Spa-Francorchamps', 'Belgium', '401');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('63', 'sebring', 'Sebring International Raceway', 'USA', '18');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('48', 'mosport', 'Mosport International Raceway', 'Canada', '332');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('46', 'watkins_glen', 'Watkins Glen', 'USA', '485');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('14', 'monza', 'Autodromo Nazionale di Monza', 'Italy', '162');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('33', 'phoenix', 'Phoenix street circuit', 'USA', '345');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('11', 'hungaroring', 'Hungaroring', 'Hungary', '264');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('26', 'jerez', 'Circuito de Jerez', 'Spain', '37');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('28', 'okayama', 'Okayama International Circuit', 'Japan', '266');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('34', 'ricard', 'Circuit Paul Ricard', 'France', '432');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('52', 'tremblant', 'Circuit Mont-Tremblant', 'Canada', '214');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('19', 'indianapolis', 'Indianapolis Motor Speedway', 'USA', '223');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('27', 'estoril', 'Autodromo do Estoril', 'Portugal', '130');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('12', 'valencia', 'Valencia Street Circuit', 'Spain', '4');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('31', 'donington', 'Donington Park', 'UK', '88');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('5', 'istanbul', 'Istanbul Park', 'Turkey', '130');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('32', 'rodriguez', 'Autodromo Hermanos Rodri­guez', 'Mexico', '2227');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('2', 'sepang', 'Sepang International Circuit', 'Malaysia', '18');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('49', 'montjuic', 'Montjuic', 'Spain', '79');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('62', 'monsanto', 'Monsanto Park Circuit', 'Portugal', '158');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('64', 'ain-diab', 'Ain Diab', 'Morocco', '19');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('75', 'portimao', 'Autodromo Internacional do Algarve', 'Portugal', '108');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('77', 'jeddah', 'Jeddah Corniche Circuit', 'Saudi Arabia', '15');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('7', 'villeneuve', 'Circuit Gilles Villeneuve', 'Canada', '13');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('1', 'albert_park', 'Albert Park Grand Prix Circuit', 'Australia', '10');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('8', 'magny_cours', 'Circuit de Nevers Magny-Cours', 'France', '228');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('58', 'aintree', 'Aintree', 'UK', '20');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('47', 'anderstorp', 'Scandinavian Raceway', 'Sweden', '153');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('45', 'jarama', 'Jarama', 'Spain', '609');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('22', 'suzuka', 'Suzuka Circuit', 'Japan', '45');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('16', 'fuji', 'Fuji Speedway', 'Japan', '583');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('42', 'dallas', 'Fair Park', 'USA', '139');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('55', 'reims', 'Reims-Gueux', 'France', '88');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('40', 'zolder', 'Zolder', 'Belgium', '36');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('18', 'interlagos', 'Autodromo Jose Carlos Pace', 'Brazil', '785');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('25', 'galvez', 'Autodromo Juan y Oscar Galvez', 'Argentina', '8');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('15', 'marina_bay', 'Marina Bay Street Circuit', 'Singapore', '18');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('6', 'monaco', 'Circuit de Monaco', 'Monaco', '7');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('76', 'mugello', 'Autodromo Internazionale del Mugello', 'Italy', '255');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('56', 'george', 'Prince George Circuit', 'South Africa', '15');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('35', 'yeongam', 'Korean International Circuit', 'Korea', '0');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('69', 'americas', 'Circuit of the Americas', 'USA', '161');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('20', 'nurburgring', 'Nurburgring', 'Germany', '578');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('78', 'losail', 'Losail International Circuit', 'Qatar', NULL);
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('70', 'red_bull_ring', 'Red Bull Ring', 'Austria', '678');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('29', 'adelaide', 'Adelaide Street Circuit', 'Australia', '58');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('61', 'avus', 'AVUS', 'Germany', '53');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('9', 'silverstone', 'Silverstone Circuit', 'UK', '153');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('3', 'bahrain', 'Bahrain International Circuit', 'Bahrain', '7');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('57', 'zeltweg', 'Zeltweg', 'Austria', '676');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('65', 'pescara', 'Pescara Circuit', 'Italy', '129');
INSERT INTO circuits (circuit_id, circuit_ref, circuit_name, country, meters_above_sl) VALUES ('50', 'nivelles', 'Nivelles-Baulers', 'Belgium', '139');
